--TRANFORMAR EM FUNÇÃO


--Se vir  so uma linha select into,se vir mais de uma    

DECLARE 
    V_IDDEPT NUMBER (3);

BEGIN 
     V_IDDEPT:70;
    FOR RS IN (SELECT EMPLOYEE_ID,FIRST_NAME NOME,SALARY,
                SALARY * 2 AS SALARIO_MUTIPLICADO 
                FROM EMPLOYEES WHERE DEPARTMENT_ID= V_IDDEPT) 
    LOOP
        DBMS_OUTPUT.PUT_LINE('NOME DO FUNCIONARIO  ' || RS.NOME ||'SALARIO:' || RS.SALARY);
    END LOOP
     DBMS_OUTPUT.PUT_LINE('FIM');
END;

CREATE OR REPLACE
FUNCTION  FUNC_TESTE(P_IDDEPARAMENTO IN EMPLOYEES.DEPARTMENT_ID%TYPE)
RETURN NUMBER 
IS
BEGIN 
    FOR RS IN (SELECT EMPLOYEE_ID,FIRST_NAME NOME,SALARY,
                SALARY * 2 AS SALARIO_MUTIPLICADO 
                FROM EMPLOYEES WHERE DEPARTMENT_ID= P_IDDEPARAMENTO) 
    LOOP
        DBMS_OUTPUT.PUT_LINE('NOME DO FUNCIONARIO  ' || RS.NOME ||'SALARIO:' || RS.SALARY);
    END LOOP
     DBMS_OUTPUT.PUT_LINE('FIM');
END;


---BLOCO PLSQL PARA EXECUTAR UMA FUNCTION

 DECLARE 
        RET NUMBER ;
   BEGIN
        RETC := FUNC_AUMENTOSALARIOPESSOA(1,10);
        DBMS_OUTPUT.PUT_LINE('RETORNOU  ' || RET);
   END;

