
    DROP TABLE PRODUTO_VENDA
    CREATE TABLE PRODUTO_VENDA(
        ID NUMBER(4) PRIMARY KEY,
        NOME VARCHAR (120) NOT NULL,
        PRECO_VENDA NUMBER(10,2) NULL,
        PRECO_MEDIO_COMPRA NUMBER (10,2) NOT NULL,
        ATIVO CHAR(1) NOT NULL,
        CONSTRAINT CK_ATIVO_PRODUTO CHECK (ATIVO IN ('S','N'))
    );
    ------------------------------------------------------------------------------

    INSERT INTO PRODUTO_VENDA(ID,NOME,PRECO_VENDA, PRECO_MEDIO_COMPRA,ATIVO)
        VALUES (1, 'CANETA AZUL', NULL,0.85,'S');

    INSERT INTO PRODUTO_VENDA(ID,NOME,PRECO_VENDA, PRECO_MEDIO_COMPRA,ATIVO)
        VALUES (2, 'APAGADOR',1.35,1,'S');

    INSERT INTO PRODUTO_VENDA(ID,NOME,PRECO_VENDA, PRECO_MEDIO_COMPRA,ATIVO)
        VALUES (2, 'CLIPS',0.05,0.01,'N');

    INSERT INTO PRODUTO_VENDA(ID,NOME,PRECO_VENDA, PRECO_MEDIO_COMPRA,ATIVO)
        VALUES (2, 'MARTELO',12,7,'S');
    
COMMIT;

SELECT *FROM PRODUTO_VENDA ;
------------------------------------------------------------------------------------
--NAO PODE TER PRODUTO COM MENOS DE 20% DE MARGEM 
-- SE O PRODUTO TEM MARGEM MAIOR QUE O PARAMETRO NAO MEXER COM O VALOR DA VENDA 

CREATE OR REPLACE 
FUNCTION FUNC_CALCPRECOVENDA(P_PERC_MARGEM IN NUMBER)
RETURN NUMBER 
IS 
V_NOVO_PRECO_VENDA PRODUTO_VENDA.PRECO_VENDA%TYPE;

BEGIN 
    IF P_PERC_MARGEM >= 0 AND P_PERC_MARGEM <=100 THEN 
        FOR RS IN (SELECT ID, NVL (PRECO_VENDA, 0) PRECO_VENDA ,PRECO_MEDIO_COMPRA
                FROM PRODUTO_VENDA WHERE ATIVO ='S')
        LOOP
          DBMS_OUTPUT.PUT_LINE('ID:'||RS.ID);
          DBMS_OUTPUT.PUT_LINE('PRECO_VENDA:'||RS.PRECO_VENDA);
          DBMS_OUTPUT.PUT_LINE('PRECO_MEDIO_COMPRA:'||RS.PRECO_MEDIO_COMPRA);
          DBMS_OUTPUT.PUT_LINE('P_PERC_MARGEM:'||P_PERC_MARGEM);
          DBMS_OUTPUT.PUT_LINE('NOVO PREÇO DE VENDA:'||
            ( RS.PRECO_MEDIO_COMPRA + (RS.PRECO_MEDIO_COMPRA *(P_PERC_MARGEM/100))));
          V_NOVO_PRECO_VENDA:=( RS.PRECO_MEDIO_COMPRA + (RS.PRECO_MEDIO_COMPRA *(P_PERC_MARGEM/100)));
          IF  V_NOVO_PRECO_VENDA> RS.PRECO_VENDA THEN 
                UPDATE PRODUTO_VENDA SET PRECO_VENDA = V_NOVO_PRECO_VENDA
                WHERE ID = RS.ID;
          END IF;
          DBMS_OUTPUT.PUT_LINE('----------------------------------------------');

        END LOOP;
        COMMIT;
        RETURN 0;
    ELSE
        RETURN -1;-- FORA DA FAIXA DE PORCENTUAL DE MARGEM 
    END IF;
EXCEPTION  
WHEN OTHERS THEN 
    ROLLBACK;
    RETURN SQLCODE;
END;

----------------------------------------- CHAMADA DA FUNÇÃO -EXECUTAR ------------------------------
DECLARE 
   RETORNO NUMBER (5);
BEGIN 
    RETORNO:= FUNC_CALCPRECOVENDA (20);
    DBMS_OUTPUT.PUT_LINE('DO CODIGO DA CHAMADA-->: RETORNO'||RETORNO);
END;