DECLARE    
    V_IDDEPT NUMBER(3);BEGIN    V_IDDEPT := 70; -- poderia ser 999 também 
        FOR RS IN (SELECT EMPLOYEE_ID,FIRST_NAME NOME,SALARY,SALARY * 2 AS SALARIO_MULTIPLICADO        
            FROM EMPLOYEES WHERE DEPARTMENT_ID = V_IDDEPT) 
        LOOP DBMS_OUTPUT.PUT_LINE('NOME DO FUNCIONARIO: ' || RS.NOME ||' SALARIO: ' || RS.SALARY );
    END LOOP;
    DBMS_OUTPUT.PUT_LINE('FIM');
    END;
