---------------------------------------------FAZER COPIA DE LINHAS E COLUNAS DAS TABELAS-----------------------------------------------------
CREATE TABLE FUNCIONARIOS_PAH AS (SELECT* FROM HR.EMPLOYEES); -- SALVAR NO MEU NOME O BANCO RESERVA

SELECT * FROM EMPLOYEES;

--CRIAR UMA FUNCAO QUE AUMENTE OS SALARIOS DOS FUNCIONARIOS,
--ESTA FUNCAO DEVE TER COMO PARAMENTRO DE ENTRADA O INDICE DE AUMENTO,
--QUE DEVE ESTAR ENTRE 0 MAIOR QUE ZERO E 15 PORCENTUAIS (MENOR IGUAL).
--TODOS DEVEM TER UM AUMENTO MENOS O PRESIDENTE E O VICE PRECIDENTE, 
--O TETO DE SALARIO DE UM FUNCIONRIOS DEVE SER 10000,
--MAS SE JA GANHA MIS QUE OS 10000 DEVE FICAR COM O SALARIO ATUAL QUE É MAIOR QUE 10000 ACRESCIDO DO PORCENTUAL DE AUMENTO.

CREATE OR REPLACE 
FUNCTION FUNC_AUMENT_SALARIO(P_INDICE_AUMENT IN NUMBER)
RETURN NUMBER
IS 
    V_RET NUMBER(5);
    V_SALARY_NOVO  FUNCIONARIOS_PAH.SALARY%TYPE;

BEGIN 
    IF P_INDICE_AUMENT> 0 AND P_INDICE_AUMENT <= 15 THEN
         FOR RS IN (SELECT ID,SALARY
                FROM FUNCIONARIOS_PAH WHERE JOB_ID !=1 AND JOB_ID !=2 )
        LOOP
            IF()
        V_RET:=0;-- TUDO OK 
    ELSE 
    V_RET :=-1; ----- FORA DA FAIXA DE PORCENTUAL DO INDICE 
    END IF;


    -- WHERE AD_PRES(1) AD_VP(2)  ----- JOB_ID