DECLARE
    IDADE NUMBER(3);
    V_SALARIO NUMBER(10,2):=1000;
    V_NOME VARCHAR(120);
BEGIN 
    IDADE :=35;
    IDADE :=IDADE *2;
    V_NOME:='MARIA';
    V_SALARIO:=IDADE;
    dbms_@output.put_line('A IDADE É:' || IDADE);
END;


----------------------------------------------------------
DECLARE 
    V_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
BEGIN 
    V_EMPLOYEE_ID :=105;
    SELECT FIRST_NAME INTO V_FIRST_NAME
    FROM EMPLOYEES
WHERE EMPLOYEE_ID=V_EMPLOYEE_ID;
   DBMS_OUTPUT.PUT_LINE('O NOME DO FUNCIONARIO É: ' || V_FIRST_NAME);
END;

---------------------------------------------------------
DECLARE 
    V_DEPARTMENT_ID DEPARTMENTS.DEPARTMENT_ID%TYPE;
    V_DEPARTMENT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN 
   V_EMPLOYEE_ID :=105;
    SELECT DEPARTMENT_NAME INTO V_DEPARTMENT_NAME,
    FROM DEPARTMENTS
WHERE DEPARTMENT_ID = V_DEPARTMENT_ID;

   DBMS_OUTPUT.PUT_LINE('O NOME DO DEPARTAMENTO É: ' || V_DEPARTMENT_NAME);
END; ------------DANDO ERRO-------
---------------------------------------------------------------------

---DEFINIR UMA VARIAVELC/ VALOR VALIDO P/ ID DO FUNCIONARIO E O NOME DO SEU DEPARTAMENTO QUE ELE TRABALHA ---

DECLARE 
    V_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
    V_DEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE;
    V_DEPARTMENT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN 
    V_EMPLOYEE_ID :=105;
    SELECT FIRST_NAME, DEPARTMENT_ID  INTO V_FIRST_NAME, V_DEPARTMENT_ID 
    FROM EMPLOYEES
WHERE EMPLOYEE_ID=V_EMPLOYEE_ID;
   
    SELECT DEPARTMENT_NAME INTO V_DEPARTMENT_NAME
    FROM  DEPARTMENTS
WHERE DEPARTMENT_ID = V_DEPARTMENT_ID;
   DBMS_OUTPUT.PUT_LINE('O NOME DO FUNCIONARIO É: ' || V_FIRST_NAME ||' O DEPARTAMENTO É: ' || V_DEPARTMENT_NAME);
END;



---------USANDO O JOIN E PERCEBENDO O QUANTO É MENOR O CODIGO --------------
DECLARE 
    V_EMPLOYEE_ID EMPLOYEES.EMPLOYEE_ID%TYPE;
    V_FIRST_NAME EMPLOYEES.FIRST_NAME%TYPE;
   --- V_DEPARTMENT_ID EMPLOYEES.DEPARTMENT_ID%TYPE;
    V_DEPARTMENT_NAME DEPARTMENTS.DEPARTMENT_NAME%TYPE;
BEGIN 
    V_EMPLOYEE_ID :=105;
    SELECT FIRST_NAME, DEPARTMENT_NOME  INTO V_FIRST_NAME, V_DEPARTMENT_NAME
    FROM EMPLOYEES EMP
    LEFT JOIN  DEPARTMENT DEP
    ON EMP.DEPARTMENT_ID=DEP.DEPARTMENT_ID
    WHERE EMPLOYEE_ID=V_EMPLOYEE_ID;
 
   DBMS_OUTPUT.PUT_LINE('O NOME DO FUNCIONARIO É: ' || V_FIRST_NAME ||'O NOME DO DO DEPARTAMENTO É: ' || V_DEPARTMENT_NAME);
END;
------ DANDO ERRO --------

----USANDO O IF-----



