---------EXERCICIO PEGAR O CARGO DO JOBS-----------  24/02

DECLARE 
    V_JOB_ID HR.JOBS.JOB_ID%TYPE;
    V_TITLE HR.JOBS.JOB_TITLE%TYPE; ----------HR É O AMBIENTE QUE ESTA A TABELA -------------
BEGIN 
    V_JOB_ID :='AD_VP';------- TEXTO------
    SELECT JOB_TITLE INTO V_TITLE ----------- SE NAO TIVER O INTO ELE NAO JOGA PRA LUGAR NENHUM
    FROM JOBS
WHERE JOB_ID= V_JOB_ID;
   DBMS_OUTPUT.PUT_LINE('O NOME DO CARGO  É: ' || V_TITLE);
END;



----------------------TRATANDO  EXCEPTION QUANDO NAO ACHA A LINHA DE REGISTRO NO SELECT------------------

DECLARE 
    V_JOB_ID HR.JOBS.JOB_ID%TYPE;
    V_TITLE HR.JOBS.JOB_TITLE%TYPE; ----------HR É O AMBIENTE QUE ESTA A TABELA -------------
BEGIN 
    V_JOB_ID :='AD_VP';------- TEXTO------
    SELECT JOB_TITLE INTO V_TITLE ----------- SE NAO TIVER O INTO ELE NAO JOGA PRA LUGAR NENHUM
    FROM JOBS
WHERE JOB_ID= V_JOB_ID;
   DBMS_OUTPUT.PUT_LINE('O NOME DO CARGO  É: ' || V_TITLE);
   COMMIT;
EXCEPTION  
WHEN OTHERS THEN 
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('CODIGO DO ERRO  É: ' || SQLCODE);
      DBMS_OUTPUT.PUT_LINE('DESCRICAO DO ERRO  É: ' || SQLERRM);
END;

--------------------- EXPECIFICANDO O ERRO -------------------------

DECLARE 
    V_JOB_ID HR.JOBS.JOB_ID%TYPE;
    V_TITLE HR.JOBS.JOB_TITLE%TYPE; ----------HR É O AMBIENTE QUE ESTA A TABELA -------------
BEGIN 
    V_JOB_ID :='AD_VP';------- TEXTO------
    SELECT JOB_TITLE INTO V_TITLE ----------- SE NAO TIVER O INTO ELE NAO JOGA PRA LUGAR NENHUM
    FROM JOBS
WHERE JOB_ID= V_JOB_ID;
   DBMS_OUTPUT.PUT_LINE('O NOME DO CARGO  É: ' || V_TITLE);
   COMMIT;
EXCEPTION  
WHEN NO_DATA_FOUND THEN 
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('NÃO EXISTE CARGO COM ESSE CÓDIGO: ');
WHEN OTHERS THEN 
    DBMS_OUTPUT.PUT_LINE('CODIGO DO ERRO  É: ' || SQLCODE);
      DBMS_OUTPUT.PUT_LINE('DESCRICAO DO ERRO  É: ' || SQLERRM);
END;


----------------- AQUI O CODIGO TRAZ O NUMERO QUE ESTA O ERRO NO CODIGO

DECLARE 
    V_JOB_ID HR.JOBS.JOB_ID%TYPE;
    V_TITLE HR.JOBS.JOB_TITLE%TYPE; ----------HR É O AMBIENTE QUE ESTA A TABELA -------------
    X NUMBER (1);
BEGIN 
    X := 10 / 0; 
    V_JOB_ID :='AD_VP';------- TEXTO------
    SELECT JOB_TITLE INTO V_TITLE ----------- SE NAO TIVER O INTO ELE NAO JOGA PRA LUGAR NENHUM
    FROM JOBS
WHERE JOB_ID= V_JOB_ID;
   DBMS_OUTPUT.PUT_LINE('O NOME DO CARGO  É: ' || V_TITLE);
   COMMIT;
EXCEPTION  
WHEN NO_DATA_FOUND THEN 
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('NÃO EXISTE CARGO COM ESSE CÓDIGO: ');
WHEN OTHERS THEN 
    DBMS_OUTPUT.PUT_LINE('CODIGO DO ERRO  É: ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('DESCRICAO DO ERRO  É: ' || SQLERRM);
    DBMS_OUTPUT.PUT_LINE('LINHA DO ERROÉ: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);---------- TRAZ A LINHA DO CODIGO------
END;

------------------------------------------USANDO A CONDICAO ----------------------------------------
DECLARE 
    V_JOB_ID HR.JOBS.JOB_ID%TYPE;
    V_TITLE HR.JOBS.JOB_TITLE%TYPE; 
    V_QTDE NUMBER(1);
BEGIN 
    V_JOB_ID :='ADX_VP';
    SELECT COUNT(*) INTO V_QTDE
        FROM JOBS
    WHERE JOB_ID=V_JOB_ID;
    IF V_QTDE =1 THEN ------------AQUI É A CONDICAO 
            SELECT JOB_TITLE INTO V_TITLE --------- SE FOR IGUAL A 1 VAI IMPRIMIR---------
             FROM JOBS
        WHERE JOB_ID= V_JOB_ID;
        DBMS_OUTPUT.PUT_LINE('O NOME DO CARGO  É: ' || V_TITLE);
    ELSE 
                DBMS_OUTPUT.PUT_LINE('CARGO INEXISTENTE');
 END IF;
   COMMIT;
EXCEPTION  
    
WHEN OTHERS THEN 
    ROLLBACK;
    DBMS_OUTPUT.PUT_LINE('CODIGO DO ERRO  É: ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('DESCRICAO DO ERRO  É: ' || SQLERRM);
    DBMS_OUTPUT.PUT_LINE('LINHA DO ERROÉ: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;

--------------------------------------------------------------PROCEDURE-----------
CREATE OR REPLACE
PROCEDURE PROC_RETORNANOMECARGO(P_JOBID IN HR.JOBS.JOB_ID%TYPE,
                                P_JOBTITLE OUT HR.JOBS.JOB_TITLE%TYPE,
                                P_SAIDA OUT NUMBER) ----- TRES PARAMETROS, 1 DE ENTRADA 2 SAIDA-----------
IS 
    V_QTDE NUMBER(1);
BEGIN 
    SELECT COUNT(*) INTO V_QTDE
    FROM JOBS
    WHERE JOB_ID=P_JOBID;
    IF V_QTDE =1 THEN 
            SELECT JOB_TITLE INTO P_JOBTITLE 
            FROM JOBS
        WHERE JOB_ID= P_JOBID;
       P_SAIDA:=0;
    ELSE 
     P_SAIDA:=-1; ---NAO EXISTE O CaRGO
 END IF;
   COMMIT;
EXCEPTION  
WHEN OTHERS THEN 
    ROLLBACK;
    P_SAIDA:=SQLCODE;
    DBMS_OUTPUT.PUT_LINE('CODIGO DO ERRO  É: ' || SQLCODE);
    DBMS_OUTPUT.PUT_LINE('DESCRICAO DO ERRO  É: ' || SQLERRM);
    DBMS_OUTPUT.PUT_LINE('LINHA DO ERROÉ: ' || DBMS_UTILITY.FORMAT_ERROR_BACKTRACE);
END;


------------------------------ CHAMANDO A PROCEDURE-------------------------------
DECLARE 
    NOME_CARGO HR.JOBS.JOB_TITLE%TYPE; 
    RETORNO NUMBER(5);
BEGIN 
    PROC_RETORNANOMECARGO('AD_VP',NOME_CARGO,RETORNO);
    IF RETORNO=0 THEN   
        DBMS_OUTPUT.PUT_LINE('NOME CARGO0 ' || NOME_CARGO);
ELSIF RETORNO=-1 THEN
     DBMS_OUTPUT.PUT_LINE('NAO EXISTE CARGO COM ESSE ID ');
ELSE 
     DBMS_OUTPUT.PUT_LINE('ERRO DO EXCEPTION: ' || RETORNO);
END IF ;
END;