
-------------CRIAR UMA TABELA FUNCIONARIO LAS COMPIADO DA TABELA EMPLOYEES----------------

DROP TABLE FUNCIONARIOS_LAS; 
CREATE TABLE FUNCIONARIOS_LAS AS (SELECT * FROM HR.EMPLOYEES);

---------------CRIAR TABELA E SEQUENCE DA TABELA DE LOG


DROP TABLE FUNCIONARIOS_LAS_LOG; 
CREATE TABLE FUNCIONARIOS_LAS_LOG
   ( ID_LOG NUMBER PRIMARY KEY, 
   EMPLOYEE_ID NUMBER(6) NOT NULL, 
   SALARY_VELHO NUMBER(8,2) NOT NULL, 
   SALARY_NOVO NUMBER(8,2) NOT NULL, 
   USUARIO VARCHAR2(30) NOT NULL, 
   DTH_REGISTRO DATE NOT NULL );

----------SEQUENCES--------------------

DROP SEQUENCE SEQ_FUNCIONARIOSLASLOG; 
CREATE SEQUENCE SEQ_FUNCIONARIOSLASLOG 
NOCACHE 
NOCYCLE;


-------------CRIAR TABELA DE LOGDE EXECUÇÃO----------------------


DROP TABLE LOG_EXECUCAO;

 CREATE TABLE LOG_EXECUCAO(
 ID_LOG NUMBER PRIMARY KEY,
 ERRO NUMBER NOT NULL,
 DESC_ERRO VARCHAR2(1000) NOT NULL,
 LINHA_ERRO VARCHAR2(1000) NULL,
 NOME_CODIGO VARCHAR2(30) NOT NULL,
 PARAMENTROS VARCHAR2(1000) NULL,
 DTH_ERRO DATE NOT NULL,
 USUARIO VARCHAR2(30),
 RESOLVIDO CHAR(1) NOT NULL,
 DESC_RESOLVIDO VARCHAR2(1000) NULL
 );
------------ SEQUENCE----------------
DROP SEQUENCE SEQ_LOG_EXECUCAO;
CREATE SEQUENCE SEQ_LOG_EXECUCAO
NOCACHE
NOCYCLE;


-------------------FUNCTION ------------


CREATE OR REPLACE FUNCTION FUNC_AUMENTOSALARIO (P_PERC IN NUMBER)
RETURN NUMBER
IS
 V_RET NUMBER(5);
 V_SALARY_NOVO FUNCIONARIOS_LAS.SALARY%TYPE;
----------------------------------
 V_ERRO NUMBER;
 V_DESC_ERRO VARCHAR2(1000);
----------------------------------
BEGIN

 IF P_PERC > 0 AND P_PERC <= 15 THEN
 FOR RS IN (
 SELECT EMPLOYEE_ID, SALARY FROM FUNCIONARIOS_LAS
 WHERE JOB_ID NOT IN('AD_PRES','AD_VP')
 )
 LOOP
 V_SALARY_NOVO := RS.SALARY + (RS.SALARY * (P_PERC / 100));
 IF RS.SALARY <= 10000 THEN
 IF V_SALARY_NOVO > 10000 THEN
 V_SALARY_NOVO := 10000;
 END IF;
 END IF;
 UPDATE FUNCIONARIOS_LAS SET SALARY = V_SALARY_NOVO
 WHERE EMPLOYEE_ID = RS.EMPLOYEE_ID;

 END LOOP;
 V_RET := 0; --TUDO OK
 ELSE
 V_RET := -1; --FORA DA FAIXA DE PERCENTUAL DE AUMENTO
 END IF;
 COMMIT;
 RETURN V_RET;
EXCEPTION
 WHEN OTHERS THEN
 ROLLBACK;
-----------------------------------------
 V_ERRO := SQLCODE;
 V_DESC_ERRO := SQLERRM;

 INSERT INTO LOG_EXECUCAO(ID_LOG, ERRO, DESC_ERRO, LINHA_ERRO, NOME_CODIGO, PARAMENTROS,
 DTH_ERRO, USUARIO, RESOLVIDO, DESC_RESOLVIDO)
 VALUES(
 SEQ_LOG_EXECUCAO.NEXTVAL,
 V_ERRO,
 V_DESC_ERRO,
 DBMS_UTILITY.FORMAT_ERROR_BACKTRACE,
 'FUNC_AUMENTOSALARIO',
 'P_PERC = ' || P_PERC,
 SYSDATE,
 USER,
 'N',
 NULL
 );
 COMMIT;
-------------------------------------------------
 RETURN SQLCODE;
END;



----------SCRIPT PARA EXECUTAR FUNCTION-------------

DECLARE RETORNO NUMBER(5);
BEGIN RETORNO := FUNC_AUMENTOSALARIO(10); DBMS_OUTPUT.PUT_LINE('RETORNO = ' || RETORNO); 
END;


---------SELECT DO LOG DE REGISTRO-------------------

SLECT ID_LOG, EMPLOYEE_ID, SALARY_VELHO, SALARY_NOVO, TO_CHAR(DTH_REGISTRO, 'DD/MM/YYYY HH24:MI:SS'), USUARIO FROM FUNCIONARIOS_LAS_LOG  ORDER BY DTH_REGISTRO DESC;

----------UPDATE PELO CLIENT NÃO REGISTRA LOG-------------

SELECT * FROM FUNCIONARIOS_LAS;

UPDATE FUNCIONARIOS_LAS SET SALARY = 9500 WHERE EMPLOYEE_ID = 103;

COMMIT;

SELECT ID_LOG, EMPLOYEE_ID, SALARY_VELHO, SALARY_NOVO,

TO_CHAR(DTH_REGISTRO, 'DD/MM/YYYY HH24:MI:SS'), 
USUARIO FROM FUNCIONARIOS_LAS_LOG ORDER BY DTH_REGISTRO DESC;

----------CRIANDO TRIGGERS-----------------------

CREATE OR REPLACE TRIGGER TRG_LOG_FUNCIONARIOSLAS
BEFORE INSERT OR UPDATE OF SALARY
ON FUNCIONARIOS_LAS
FOR EACH ROW
BEGIN
   INSERT INTO FUNCIONARIOS_LAS_LOG
            (ID_LOG, EMPLOYEE_ID, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO)
 VALUES(SEQ_FUNCIONARIOSLASLOG.NEXTVAL, :NEW.EMPLOYEE_ID, :OLD.SALARY, :NEW.SALARY, USER, SYSDATE);
END;



--------------------------------------------------------

CREATE TABLE LOG_REGISTRO(
 ID_LOG NUMBER PRIMARY KEY,
 OPERACAO CHAR(1),
 );

DROP SEQUENCE SEQ_LOG_EXECUCAO;

 CREATE SEQUENCE SEQ_LOG_EXECUCAO
 NOCACHE
 NOCYCLE;


