DROP TABLE PESSOA;


CREATE TABLE PESSOA(

ID NUMBER(3) PRIMARY KEY,
NOME VARCHAR2(20) NOT NULL,
SALARIO NUMBER (7,2) NOT NULL
);



INSERT INTO PESSOA(ID, NOME, SALARIO) VALUES (1,'MARIA', 99999,99);
INSERT INTO PESSOA(ID, NOME, SALARIO) VALUES (2,'PAULO', -99999,99);
COMMIT;

SELECT * FROM PESSOA;




CREATE OR REPLACE TRIGGER TRG_VALIDAPESSOA
BEFORE INSERT OR UPDATE OF SALARIO
ON PESSOA
FOR EACH ROW
BEGIN
    IF :NEW.SALARIO <= 0 OR :NEW.SALARIO > 10000 THEN
        RAISE_APPLICATION_ERROR(-20000, 'SALARIO FORA DA FAIXA DE VALOR');
    END IF;
END;

INSERT INTO PESSOA(ID, NOME, SALARIO) VALUES (1,'CLAUDIA ', 99999,99);
INSERT INTO PESSOA(ID, NOME, SALARIO) VALUES (2,'EVERTON', -99999,99);



UPDATE PESSOA SET SALARIO = 2000 WHERE ID = 5;




--------------------------------------
------------EXERCICIO 

DROP TABLE MEDIAS_ALUNO;

CREATE TABLE MEDIAS_ALUNO(
    RA NUMBER(7) PRIMARY KEY,
    MEDIA NUMBER (4,2) NOT NULL,
    FREQUENCIA NUMBER(5,2) NOT NULL
);

--CRIAR UMA TRIGGER QUE SO DEIXA ENTRAR VALOR ENTRE 0 E 10 NA COLUNA MEDIA.
-- FAÇAM INSERTS E UPDATES NESSA COLUNA PARA VALIDAR SEU CODIGO 
---ADAPTE SUA TRIGGER PARA NA COLUNA FRQUENCIA ACEITAR NUMEROS DE 0 A 100.

CREATE OR REPLACE TRIGGER TRG_VALIDAPESSOA
BEFORE INSERT OR UPDATE OF MEDIA, FREQUENCIA
ON MEDIAS_ALUNO
FOR EACH ROW
BEGIN
    IF :NEW.MEDIA<0 OR :NEW.MEDIA >10 THEN 
        RAISE_APPLICATION_ERROR( -20000, 'MEDIA FORA DA FAIXA DE 0 A 10');
    END IF;
    IF :NEW.FREQUENCIA < 0 OR :NEW.FREQUENCIA >100 THEN 
        RAISE_APPLICATION_ERROR( -20001, 'FREQUENCIA DEVE ESTAR ENTRE 0 E 100');
    END IF;

END;


INSERT INTO PESSOA(RA, MEDIA, FREQUENCIA) VALUES (1,'20 ', 2);
INSERT INTO PESSOA(ID, NOME, SALARIO) VALUES (2,'EVERTON', -99999,99);


SELECT * FROM PESSOA;

UPDATE PESSOA SET SALARIO =88888.88
WHERE ID=1;
COMMIT;

UPDATE PESSOA SET NOME ='PEDRO',SALARIO =70000
WHERE ID=1;
COMMIT;