-----------------------------------------RECOSNTRUIR TABELA LOG_RESGISTRO-----------------------------------------------------------
DROP TABLE FUNCIONARIOS_LAS; 
CREATE TABLE FUNCIONARIOS_LAS AS (SELECT * FROM HR.EMPLOYEES);
-------------------------------------------------------CRIACAO DA TABELA FUNCIONARIO ----------------------------------------

DROP TABLE FUNCIONARIOS_LAS_LOG; 
CREATE TABLE FUNCIONARIOS_LAS_LOG( ID_LOG NUMBER PRIMARY KEY, 
EMPLOYEE_ID NUMBER(6) NOT NULL, 
SALARY_VELHO NUMBER(8,2) NULL, 
SALARY_NOVO NUMBER(8,2) NULL, 
USUARIO VARCHAR2(30) NOT NULL, 
DTH_REGISTRO DATE NOT NULL );



DROP SEQUENCE SEQ_FUNCIONARIOSLASLOG; 
CREATE SEQUENCE SEQ_FUNCIONARIOSLASLOG NOCACHE NOCYCLE;

--------------------------TABELA DE LOG EXECUCAO --------------------------------------
DROP TABLE LOG_EXECUCAO;

 CREATE TABLE LOG_EXECUCAO(
 ID_LOG NUMBER PRIMARY KEY,
 ERRO NUMBER NOT NULL,
 DESC_ERRO VARCHAR2(1000) NOT NULL,
 LINHA_ERRO VARCHAR2(1000) NULL,
 NOME_CODIGO VARCHAR2(30) NOT NULL,
 PARAMENTROS VARCHAR2(1000) NULL,
 DTH_ERRO DATE NOT NULL,
 USUARIO VARCHAR2(30),
 RESOLVIDO CHAR(1) NOT NULL,
 DESC_RESOLVIDO VARCHAR2(1000) NULL,
 OPERACAO CHAR(1) NOT NULL

 );

DROP SEQUENCE SEQ_LOG_EXECUCAO;

 CREATE SEQUENCE SEQ_LOG_EXECUCAO
 NOCACHE
 NOCYCLE;

CREATE OR REPLACE TRIGGER TRG_LOG_FUNCIONARIOSLAS
BEFORE DELETE INSERT OR UPDATE OF SALARY
ON FUNCIONARIOS_LAS
FOR EACH ROW
BEGIN
   IF INSERTING THEN 
      INSERT INTO FUNCIONARIOS_LAS_LOG
            (ID_LOG, EMPLOYEE_ID, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO, OPERACAO)
 VALUES(SEQ_FUNCIONARIOSLASLOG.NEXTVAL, :NEW.EMPLOYEE_ID, :OLD.SALARY, :NEW.SALARY, USER, SYSDATE, 'I');
   
   ELSEIF UPDATING THEN 
            INSERT INTO FUNCIONARIOS_LAS_LOG
            (ID_LOG, EMPLOYEE_ID, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO,OPERACAO)
 VALUES(SEQ_FUNCIONARIOSLASLOG.NEXTVAL, :NEW.EMPLOYEE_ID, :OLD.SALARY, :NEW.SALARY, USER, SYSDATE,'U');
 
  ELSEIF DELETING
  INSERT INTO FUNCIONARIOS_LAS_LOG
            (ID_LOG, EMPLOYEE_ID, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO,OPERACAO)
 VALUES(SEQ_FUNCIONARIOSLASLOG.NEXTVAL, :OLD.NEW.EMPLOYEE_ID, :OLD.SALARY, :NEW.SALARY, USER, SYSDATE,'D');
  END IF;
END;


-------------------------------------FUNCTION-----------------------------
CREATE OR REPLACE FUNCTION FUNC_AUMENTOSALARIO (P_PERC IN NUMBER)
RETURN NUMBER
IS
 V_RET NUMBER(5);
 V_SALARY_NOVO FUNCIONARIOS_LAS.SALARY%TYPE;
----------------------------------
 V_ERRO NUMBER;
 V_DESC_ERRO VARCHAR2(1000);
----------------------------------
BEGIN

 IF P_PERC > 0 AND P_PERC <= 15 THEN
 FOR RS IN (
 SELECT EMPLOYEE_ID, SALARY FROM FUNCIONARIOS_LAS
 WHERE JOB_ID NOT IN('AD_PRES','AD_VP')
 )
 LOOP
 V_SALARY_NOVO := RS.SALARY + (RS.SALARY * (P_PERC / 100));
 IF RS.SALARY <= 10000 THEN
 IF V_SALARY_NOVO > 10000 THEN
 V_SALARY_NOVO := 10000;
 END IF;
 END IF;
 UPDATE FUNCIONARIOS_LAS SET SALARY = V_SALARY_NOVO
 WHERE EMPLOYEE_ID = RS.EMPLOYEE_ID;

 END LOOP;
 V_RET := 0; --TUDO OK
 ELSE
 V_RET := -1; --FORA DA FAIXA DE PERCENTUAL DE AUMENTO
 END IF;
 COMMIT;
 RETURN V_RET;
EXCEPTION
 WHEN OTHERS THEN
 ROLLBACK;


 -----------------DESAFIO--------------
 DROP TABLE FUNCIONARIOS_LAS_LOG; 
CREATE TABLE FUNCIONARIOS_LAS_LOG( ID_LOG NUMBER PRIMARY KEY, 
EMPLOYEE_ID NUMBER(6) NOT NULL, 
SALARY_VELHO NUMBER(8,2) NULL, 
SALARY_NOVO NUMBER(8,2) NULL, 
USUARIO VARCHAR2(30) NOT NULL, 
DTH_REGISTRO DATE NOT NULL );


---------------TRIGGER--------------
CREATE OR REPLACE TRIGGER TRG_LOG_FUNCIONARIOSLAS
BEFORE DELETE INSERT OR UPDATE OF SALARY
ON FUNCIONARIOS_LAS
FOR EACH ROW
BEGIN
   IF INSERTING THEN 
      INSERT INTO FUNCIONARIOS_LAS_LOG
            (ID_LOG, EMPLOYEE_ID, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO, OPERACAO)
 VALUES(SEQ_FUNCIONARIOSLASLOG.NEXTVAL, :NEW.EMPLOYEE_ID, :OLD.SALARY, :NEW.SALARY, USER, SYSDATE, 'I','DELETE FROM FUNCIONARIOS_LAS WHERE EMPLOYEES ');
   
   ELSEIF UPDATING THEN 
            INSERT INTO FUNCIONARIOS_LAS_LOG
            (ID_LOG, EMPLOYEE_ID, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO,OPERACAO)
 VALUES(SEQ_FUNCIONARIOSLASLOG.NEXTVAL, :NEW.EMPLOYEE_ID, :OLD.SALARY, :NEW.SALARY, USER, SYSDATE,'U');
 
  ELSEIF DELETING
  INSERT INTO FUNCIONARIOS_LAS_LOG
            (ID_LOG, EMPLOYEE_ID, SALARY_VELHO, SALARY_NOVO, USUARIO, DTH_REGISTRO,OPERACAO)
 VALUES(SEQ_FUNCIONARIOSLASLOG.NEXTVAL, :OLD.NEW.EMPLOYEE_ID, :OLD.SALARY, :NEW.SALARY, USER, SYSDATE,'D');
  END IF;
END;
Trigger LOG Desafio
CREATE OR REPLACE TRIGGER TRG_LOG_FUNCIONARIOLAS
BEFORE DELETE OR INSERT OR UPDATE OF SALARY
ON FUNCIONARIOS_LAS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
                INSERT INTO FUNCIONARIOS_LAS_LOG
                  (ID_LOG, EMPLOYEE_ID, SALARY_VELHO,
                  SALARY_NOVO, USUARIO, DTH_REGISTRO, OPERACAO, SQL_VOLTA)
            VALUES(SEQ_FUNCIONARIOSLASLOG.NEXTVAL,
            :NEW.EMPLOYEE_ID, :OLD.SALARY,
            :NEW.SALARY, USER, SYSDATE, 'I',
            'DELETE FROM FUNCIONARIOS_LAS WHERE EMPLOYEE_ID = ' || :NEW.EMPLOYEE_ID  || ';'
            );
    ELSIF UPDATING THEN
        INSERT INTO FUNCIONARIOS_LAS_LOG
                  (ID_LOG, EMPLOYEE_ID, SALARY_VELHO,
                  SALARY_NOVO, USUARIO, DTH_REGISTRO, OPERACAO, SQL_VOLTA)
            VALUES(SEQ_FUNCIONARIOSLASLOG.NEXTVAL,
            :NEW.EMPLOYEE_ID, :OLD.SALARY,
            :NEW.SALARY, USER, SYSDATE, 'U',
'UPDATE FUNCIONARIOS_LAS SET SALARY = ' || :OLD.SALARY || ' WHERE EMPLOYEE_ID = ' || :OLD.EMPLOYEE_ID || ';'
            );
    ELSIF DELETING THEN
        INSERT INTO FUNCIONARIOS_LAS_LOG
          (ID_LOG, EMPLOYEE_ID, SALARY_VELHO,
          SALARY_NOVO, USUARIO, DTH_REGISTRO, OPERACAO, SQL_VOLTA)
    VALUES(SEQ_FUNCIONARIOSLASLOG.NEXTVAL,
    :OLD.EMPLOYEE_ID, :OLD.SALARY,
    :NEW.SALARY, USER, SYSDATE, 'D',
    'INSERT INTO FUNCIONARIOS_LAS '
    || ' (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES ('
    || TO_CHAR(:OLD.EMPLOYEE_ID) || ','
    || NVL2(:OLD.FIRST_NAME,   '''' || :OLD.FIRST_NAME || '''',  'NULL') || ','
    || NVL2(:OLD.LAST_NAME,    '''' || :OLD.LAST_NAME || '''',   'NULL') || ','
    || NVL2(:OLD.EMAIL,        '''' || :OLD.EMAIL || '''',       'NULL') || ','
    || NVL2(:OLD.PHONE_NUMBER, '''' || :OLD.PHONE_NUMBER || '''', 'NULL') || ','
    || NVL2(:OLD.HIRE_DATE,    'TO_DATE(''' || TO_CHAR(:OLD.HIRE_DATE, 'YYYY-MM-DD HH24:MI:SS') || ''',''YYYY-MM-DD HH24:MI:SS'')', 'NULL') || ','
    || NVL2(:OLD.JOB_ID,       '''' || :OLD.JOB_ID || '''',      'NULL') || ','
    || NVL(TO_CHAR(:OLD.SALARY), 'NULL') || ','
    || NVL(TO_CHAR(:OLD.COMMISSION_PCT), 'NULL') || ','
    || NVL(TO_CHAR(:OLD.MANAGER_ID), 'NULL') || ','
    || NVL(TO_CHAR(:OLD.DEPARTMENT_ID), 'NULL')
    || ');'
    );
    END IF;
END;
 
 