Trigger LOG Desafio
CREATE OR REPLACE TRIGGER TRG_LOG_FUNCIONARIOLAS
BEFORE DELETE OR INSERT OR UPDATE OF SALARY
ON FUNCIONARIOS_LAS
FOR EACH ROW
BEGIN
    IF INSERTING THEN
                INSERT INTO FUNCIONARIOS_LAS_LOG
                  (ID_LOG, EMPLOYEE_ID, SALARY_VELHO,
                  SALARY_NOVO, USUARIO, DTH_REGISTRO, OPERACAO, SQL_VOLTA)
            VALUES(SEQ_FUNCIONARIOSLASLOG.NEXTVAL,
            :NEW.EMPLOYEE_ID, :OLD.SALARY,
            :NEW.SALARY, USER, SYSDATE, 'I',
            'DELETE FROM FUNCIONARIOS_LAS WHERE EMPLOYEE_ID = ' || :NEW.EMPLOYEE_ID  || ';'
            );
    ELSIF UPDATING THEN
        INSERT INTO FUNCIONARIOS_LAS_LOG
                  (ID_LOG, EMPLOYEE_ID, SALARY_VELHO,
                  SALARY_NOVO, USUARIO, DTH_REGISTRO, OPERACAO, SQL_VOLTA)
            VALUES(SEQ_FUNCIONARIOSLASLOG.NEXTVAL,
            :NEW.EMPLOYEE_ID, :OLD.SALARY,
            :NEW.SALARY, USER, SYSDATE, 'U',
'UPDATE FUNCIONARIOS_LAS SET SALARY = ' || :OLD.SALARY || ' WHERE EMPLOYEE_ID = ' || :OLD.EMPLOYEE_ID || ';'
            );
    ELSIF DELETING THEN
        INSERT INTO FUNCIONARIOS_LAS_LOG
          (ID_LOG, EMPLOYEE_ID, SALARY_VELHO,
          SALARY_NOVO, USUARIO, DTH_REGISTRO, OPERACAO, SQL_VOLTA)
    VALUES(SEQ_FUNCIONARIOSLASLOG.NEXTVAL,
    :OLD.EMPLOYEE_ID, :OLD.SALARY,
    :NEW.SALARY, USER, SYSDATE, 'D',
    'INSERT INTO FUNCIONARIOS_LAS '
    || ' (EMPLOYEE_ID, FIRST_NAME, LAST_NAME, EMAIL, PHONE_NUMBER, HIRE_DATE, JOB_ID, SALARY, COMMISSION_PCT, MANAGER_ID, DEPARTMENT_ID) VALUES ('
    || TO_CHAR(:OLD.EMPLOYEE_ID) || ','
    || NVL2(:OLD.FIRST_NAME,   '''' || :OLD.FIRST_NAME || '''',  'NULL') || ','
    || NVL2(:OLD.LAST_NAME,    '''' || :OLD.LAST_NAME || '''',   'NULL') || ','
    || NVL2(:OLD.EMAIL,        '''' || :OLD.EMAIL || '''',       'NULL') || ','
    || NVL2(:OLD.PHONE_NUMBER, '''' || :OLD.PHONE_NUMBER || '''', 'NULL') || ','
    || NVL2(:OLD.HIRE_DATE,    'TO_DATE(''' || TO_CHAR(:OLD.HIRE_DATE, 'YYYY-MM-DD HH24:MI:SS') || ''',''YYYY-MM-DD HH24:MI:SS'')', 'NULL') || ','
    || NVL2(:OLD.JOB_ID,       '''' || :OLD.JOB_ID || '''',      'NULL') || ','
    || NVL(TO_CHAR(:OLD.SALARY), 'NULL') || ','
    || NVL(TO_CHAR(:OLD.COMMISSION_PCT), 'NULL') || ','
    || NVL(TO_CHAR(:OLD.MANAGER_ID), 'NULL') || ','
    || NVL(TO_CHAR(:OLD.DEPARTMENT_ID), 'NULL')
    || ');'
    );
    END IF;
END;
 
 